package script;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class FETCHOKTAUSERDETAILS {

    public static void main(String[] args) {
        // Define the base URL and user names
        int count = 0;
        String baseUrl = "https://authentication.demandbase.com/api/v1/users/";
        String[] userNames = {"sshick@kforce.com",
                "bkuehl@kforce.com",
                "swallin@kforce.com",
                "amariucci@kforce.com",
                "tsutton@kforce.com",
                "cvennard@kforce.com",
                "ebeveridge@kforce.com",
                "mthomas2@kforce.com",
                "pluper@kforce.com",
                "hhumbert@kforce.com",
                "aromero2@kforce.com",
                "bferrell@kforce.com",
                "ccleveland2@kforce.com",
                "zball@kforce.com",
                "awhitfield@kforce.com",
                "aadie@kforce.com",
                "rwhite2@kforce.com",
                "darvilli@kforce.com",
                "kmiles@kforce.com",
                "rpollock@kforce.com",
                "lnordseth@kforce.com",
                "mpelland@kforce.com",
                "dfeld@kforce.com",
                "fmikac@kforce.com",
                "skerr@kforce.com",
                "ahuber2@kforce.com",
                "rborbolla@kforce.com",
                "tmcbride@kforce.com",
                "mlongshaw@kforce.com",
                "hstinnett@kforce.com",
                "sscullion@kforce.com",
                "astaples@kforce.com",
                "man5@kforce.com",
                "tbethea@kforce.com",
                "mbickhaus@kforce.com",
                "tcage@kforce.com",
                "ccajilog@kforce.com",
                "cclark3@kforce.com",
                "rconroy2@kforce.com",
                "jdean@kforce.com",
                "bfelicioni@kforce.com",
                "rjowers@kforce.com",
                "kkumar@kforce.com",
                "elarson@kforce.com",
                "jlee3@kforce.com",
                "blong@kforce.com",
                "sluu@kforce.com",
                "ematyola@kforce.com",
                "cmcbee@kforce.com",
                "cmeyer2@kforce.com",
                "speters2@kforce.com",
                "dpope@kforce.com",
                "isaitova@kforce.com",
                "kstephens2@kforce.com",
                "mtrame@kforce.com",
                "jvalenzuela@kforce.com",
                "awhatley@kforce.com",
                "wwnuk@kforce.com",
                "jferraraccio@kforce.com",
                "sstanger@kforce.com",
                "doverway2@kforce.com",
                "jweaver2@kforce.com",
                "mblake2@kforce.com",
                "edobosz@kforce.com",
                "pkerstetter@kforce.com",
                "mgaus@kforce.com",
                "aconnick@kforce.com",
                "mdauphinee@kforce.com",
                "ltocco@kforce.com",
                "mmurray3@kforce.com",
                "lmchone@kforce.com",
                "jkellett@kforce.com",
                "kborislow@kforce.com",
                "marthur@kforce.com",
                "tberg2@kforce.com",
                "tboughner@kforce.com",
                "sbrown6@kforce.com",
                "jchalet@kforce.com",
                "ncobb@kforce.com",
                "sdicioccio@kforce.com",
                "aenglish@kforce.com",
                "vescobar@kforce.com",
                "egaskill@kforce.com",
                "mgonzalez2@kforce.com",
                "tgoodman@kforce.com",
                "nhallman@kforce.com",
                "thawking@kforce.com",
                "djackson2@kforce.com",
                "ajensen@kforce.com",
                "akidd@kforce.com",
                "rkocur@kforce.com",
                "mkoleini@kforce.com",
                "nmanuelli@kforce.com",
                "emarvin@kforce.com",
                "smayfield@kforce.com",
                "bmeasures@kforce.com",
                "jmigdal@kforce.com",
                "cmontgomery@kforce.com",
                "lmoseley@kforce.com",
                "breardon@kforce.com",
                "rsoler@kforce.com",
                "tspjut@kforce.com",
                "jtaylor4@kforce.com",
                "rvolta@kforce.com",
                "dweiss2@kforce.com",
                "kbailey2@kforce.com",
                "jfields@kforce.com",
                "mkeen@kforce.com",
                "cspradlin@kforce.com",
                "krogers2@kforce.com",
                "tcloran@kforce.com",
                "jbergman@kforce.com",
                "gbaker2@kforce.com",
                "gazimiaraghi@kforce.com",
                "jjones3@kforce.com",
                "jirvine@kforce.com",
                "malton@kforce.com",
                "rconnell@kforce.com",
                "sphillips2@kforce.com",
                "smcdonald2@kforce.com",
                "kspellman@kforce.com",
                "mlinahan@kforce.com",
                "cold2@kforce.com",
                "craver@kforce.com",
                "kbosworth@kforce.com",
                "mbyrne2@kforce.com",
                "ccabianca@kforce.com",
                "mcoughlin2@kforce.com",
                "tdoton@kforce.com",
                "dfritz@kforce.com",
                "khomer@kforce.com",
                "mhowell3@kforce.com",
                "ahuffman@kforce.com",
                "sjang@kforce.com",
                "gklein@kforce.com",
                "jmaman@kforce.com",
                "mmoore3@kforce.com",
                "srubin2@kforce.com",
                "bthomas3@kforce.com",
                "cviazanko@kforce.com",
                "cvines2@kforce.com",
                "atoth@kforce.com",
                "lsantin@kforce.com",
                "ajohnson@kforce.com",
                "efitzpatrick@kforce.com",
                "dwilcox@kforce.com",
                "adeddens@kforce.com",
                "ssoares@kforce.com",
                "dcarroll@kforce.com",
                "pfloyd@kforce.com",
                "alynch@kforce.com",
                "aschamore@kforce.com",
                "bbarrett@kforce.com",
                "dbumpus@kforce.com",
                "tnordman@kforce.com",
                "cjohnson@kforce.com",
                "ddefusco@kforce.com",
                "rlynch@kforce.com",
                "jpflieger@kforce.com",
                "dbooker@kforce.com",
                "wsharp@kforce.com",
                "shealy@kforce.com",
                "jsolomon@kforce.com",
                "apeterson@kforce.com",
                "vgioia@kforce.com",
                "yobukhova@kforce.com",
                "cdahlke@kforce.com",
                "gmorris@kforce.com",
                "dtyrie@kforce.com",
                "dgarrett@kforce.com",
                "wwebster@kforce.com",
                "jbrady@kforce.com",
                "rborio@kforce.com",
                "lwagner@kforce.com",
                "mkrimmel@kforce.com",
                "relder@kforce.com",
                "nvoysest@kforce.com",
                "agagliardo@kforce.com",
                "jwallin@kforce.com",
                "bwarder@kforce.com",
                "along3@kforce.com",
                "jgoodwin@kforce.com",
                "jperrin@kforce.com",
                "lmcdonald@kforce.com",
                "sutz@kforce.com",
                "acohen@kforce.com",
                "amotal@kforce.com",
                "mcollier@kforce.com",
                "ysingh@kforce.com",
                "kburmeister@kforce.com",
                "ssnow@kforce.com",
                "jmoynihan@kforce.com",
                "tblack@kforce.com",
                "cnazarko@kforce.com",
                "asivak@kforce.com",
                "mlovett@kforce.com",
                "sbrawley@kforce.com",
                "kcasarano@kforce.com",
                "skunze@kforce.com",
                "mfrost@kforce.com",
                "bogle@kforce.com",
                "gyoo@kforce.com",
                "dcasilio@kforce.com",
                "mmerchant@kforce.com",
                "kmcdowell@kforce.com",
                "mharte@kforce.com",
                "johanesianbayle@kforce.com",
                "bprideaux@kforce.com",
                "espivey@kforce.com",
                "mdelavega@kforce.com",
                "mmcneil@kforce.com",
                "dlyons2@kforce.com",
                "mehnow@kforce.com",
                "evanderpool@kforce.com",
                "smaxwell@kforce.com",
                "dfulton@kforce.com",
                "cmedina@kforce.com",
                "htran@kforce.com",
                "rbaez@kforce.com",
                "klefler@kforce.com",
                "khagelberg@kforce.com",
                "rphillips3@kforce.com",
                "rfitzpatrick@kforce.com",
                "wlockley@kforce.com",
                "smiller@kforce.com",
                "mpagnotta@kforce.com",
                "cmurtagh@kforce.com",
                "jmartin@kforce.com",
                "tkipibondarchuk@kforce.com",
                "poyeku@kforce.com",
                "ctumminia@kforce.com",
                "mfranzoni@kforce.com",
                "jpadilla@kforce.com",
                "wwyatt@kforce.com",
                "lohlssonlewis@kforce.com",
                "rcook@kforce.com",
                "arooney@kforce.com",
                "tst-np-validate@kforce.com",
                "jward@kforce.com",
                "skothiyal@kforce.com",
                "jroundy@kforce.com",
                "clogan@kforce.com",
                "nphelps@kforce.com",
                "kogara@kforce.com",
                "ppont@kforce.com",
                "rburdon@kforce.com",
                "rlohman@kforce.com",
                "abremer@kforce.com",
                "jmaldonado@kforce.com",
                "ahershey@kforce.com",
                "khouse@kforce.com",
                "plong@kforce.com",
                "sneuschwanger@kforce.com",
                "pwilson@kforce.com",
                "smckay@kforce.com",
                "ecurtiss@kforce.com",
                "jdellipaoli@kforce.com",
                "cmeltzer@kforce.com",
                "jroyster@kforce.com",
                "lpaulson@kforce.com",
                "aanderson2@kforce.com",
                "tgarland@kforce.com",
                "brankey@kforce.com",
                "smlavery@kforce.com",
                "ehorne@kforce.com",
                "ksimon@kforce.com",
                "sfoy@kforce.com",
                "pfeliciano@kforce.com",
                "rjohnstone@kforce.com",
                "rburker@kforce.com",
                "mrussell@kforce.com",
                "kwright@kforce.com",
                "bmumford@kforce.com",
                "dpadgett@kforce.com",
                "rbiddy@kforce.com",
                "mpratt@kforce.com",
                "srodriguez2@kforce.com",
                "hberthiaume@kforce.com",
                "fedwards@kforce.com",
                "bolrich@kforce.com",
                "eeklund@kforce.com",
                "mhagan@kforce.com",
                "aholsapple@kforce.com",
                "rwallace@kforce.com",
                "mperez3@kforce.com",
                "lnicoletti2@kforce.com",
                "ppattillo@kforce.com",
                "mcunningham@kforce.com",
                "jkeefe@kforce.com",
                "lbutts@kforce.com",
                "aasberry@kforce.com",
                "ppizarrogonzalez@kforce.com",
                "jmoberg@kforce.com",
                "mfeiner@kforce.com",
                "cdye@kforce.com"};

        // Loop through the user names and make API calls
        for (String userName : userNames) {
            try {
                // Define the complete URL for the API request
                String apiUrl = baseUrl + userName;

                // Create a URL object
                URL url = new URL(apiUrl);

                // Open a connection to the URL
                HttpURLConnection connection = (HttpURLConnection) url.openConnection();

                // Set request method to GET
                connection.setRequestMethod("GET");

                // Set headers
                connection.setRequestProperty("Accept", "application/json");
                connection.setRequestProperty("Content-Type", "application/json");
                connection.setRequestProperty("Authorization", "SSWS 00smxHLPJbO5cdExEAwWN9yWmkfKCriQd--rc4AeeD");
                connection.setRequestProperty("Cookie", "JSESSIONID=2E0FAEF851E3F5672C26873CBBC6D60A; JSESSIONID=47360405109C0513D212DE803FABEB61");

                // Get the response code
                int responseCode = connection.getResponseCode();

                // Check if the response code is HTTP 200 (OK)
                if (responseCode == HttpURLConnection.HTTP_OK) {
                    // Read the response
                    BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                    String line;
                    StringBuilder response = new StringBuilder();

                    while ((line = reader.readLine()) != null) {
                        response.append(line);
                    }

                    reader.close();

                    // Print the response
                    System.out.println("API Response for user " + userName + ":");
                    if (response.length() > 200){
                        count++;
                    }
                    System.out.println(response.toString());
                } else {
                    System.out.println("API request failed with response code: " + responseCode);
                }

                // Close the connection
                connection.disconnect();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        System.out.println("Count: "+count);
    }
}
