apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: myapp





    apiVersion: v1
    kind: Service
    metadata:
      name: image-processing
      labels:
        app: myapp
    spec:
      # type: ClusterIP
      ports:
        - port: 80
          targetPort: 8080
      selector:
        tier: backend



        apiVersion: v1
        kind: Service
        metadata:
            name: image-processing
            labels:
                app: myapp
        spec:
            ports:
                -port: 80
                 targetPort: 80
            selector:
                tier: backend

